# vim: set et ts=2 sw=2 tw=80 :
name: Services
base_path: /linode/services
description: >
  Services endpoints provide a means of viewing <a href="#object-service">
  service objects</a>.
endpoints:
  linode/services:
    type: list
    resource: services
    description: >
      Returns collection of services.
    methods:
      GET:
        description: >
          Returns list of <a href="#object-service">services</a>.
        examples:
          curl: |
            curl https://$api_root/$version/linode/services
          python: |
            import services
            TODO
  linode/services/:id:
    type: resource
    resource: services
    description: >
      Returns information about a specific service offered by Linode.
    methods:
      GET:
        description: >
          Returns information about this <a href="#object-service">service</a>.
        examples:
          curl: |
            curl https://$api_root/$version/linode/services/$service_id
          python: |
            import services
            TODO
